### ISSUE TITLE
unable to execute ./run watch

### ISSUE THREAD

**Issue by battlemidget** [canonical-docs/conjure-up-docs#36]
Not sure if this is an error on my end or not but running

`./run watch`

Results in the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/documentation-builder", line 17, in <module>
    cli.main(sys.argv[1:])
  File "/usr/local/lib/python3.5/dist-packages/ubuntudesign/documentation_builder/cli.py", line 164, in main
    Builder(**arguments)
  File "/usr/local/lib/python3.5/dist-packages/ubuntudesign/documentation_builder/builder.py", line 113, in __init__
    output_path
  File "/usr/local/lib/python3.5/dist-packages/ubuntudesign/documentation_builder/operations.py", line 223, in prepare_version_branches
    Repo.clone_from(base_directory, branch_base_directory, branch=name)
  File "/usr/local/lib/python3.5/dist-packages/git/repo/base.py", line 966, in clone_from
    return cls._clone(git, url, to_path, GitCmdObjectDB, progress, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/git/repo/base.py", line 912, in _clone
    finalize_process(proc, stderr=stderr)
  File "/usr/local/lib/python3.5/dist-packages/git/util.py", line 155, in finalize_process
    proc.wait(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/git/cmd.py", line 335, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: 'git clone --branch=stable -v . /home/shared/.cache/documentation-builder/tmpv2fjxf8m' returned with exit code 128
stderr: 'Cloning into '/home/shared/.cache/documentation-builder/tmpv2fjxf8m'...
fatal: Remote branch stable not found in upstream origin
fatal: The remote end hung up unexpectedly
'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by evilnick** [comment]
Hmm, I'll take a look.

**Comment by evilnick** [comment]
The run script now tries to build the whole site, which means that it expects to find all the relevant publishable branches locally - essentially you need to git fetch 2.1.2, devel etc
It isn't great, because it is fiddly to maintain when you are running on a fork. I did mention this to @nottrobin previously. 

The easier solution may be to simply run documentation-builder in the root of the directory to build a local version of whatever you are working on.

Also, we should really have the demo-builder running on here so that PRs automatically build a version of docs from a PR
